// add cache tags here

export enum CacheTag {
  myTeam = "myTeam",
  ideation = "ideation",
  me = "me",
  logout = "logout",
  features = "features",
  feature = "feature",
  resources = "resources",
  techStack = "tech-stack",
  fetchAllSprints = "fetchAllSprints",
  sprints = "sprints",
  sprintMeetingId = "sprintMeetingId",
  sprint1 = "sprint-1",
  sprint2 = "sprint-2",
  sprint3 = "sprint-3",
  sprint4 = "sprint-4",
  sprint5 = "sprint-5",
  sprint6 = "sprint-6",
  weeklyCheckInForm = "weeklyCheckInForm",
  voyageProjectSubmissionForm = "voyageProjectSubmissionForm",
  submitWeeklyCheckinForm = "submitWeeklyCheckinForm",
  submitVoyageProjectForm = "submitVoyageProjectForm",
}
